import type { EventRecord } from "./types";

/**
 * Bundled sample events (Twin Cities metro, June 2026).
 * Used automatically when EVENTS_CSV_URL is not set, so the app runs out of the box.
 * In production these are replaced by published rows from your Google Sheet.
 */
export const sampleEvents: EventRecord[] = [
  {
    "id": "1",
    "title": "Trampled by Turtles",
    "category": "music",
    "venue": "First Avenue",
    "address": "701 First Ave N",
    "city": "Minneapolis",
    "lat": 44.9785,
    "lng": -93.276,
    "start": "2026-06-14T20:00",
    "end": "2026-06-14T23:00",
    "price": "$45",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Duluth's bluegrass juggernaut returns to the Mainroom for a hometown-adjacent throwdown. Doors at 7, 18+.",
    "image": "linear-gradient(135deg,#3a2d5e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "2",
    "title": "Twins vs. Brewers",
    "category": "sports",
    "venue": "Target Field",
    "address": "1 Twins Way",
    "city": "Minneapolis",
    "lat": 44.9817,
    "lng": -93.2776,
    "start": "2026-06-14T13:10",
    "end": "2026-06-14T16:00",
    "price": "$18–$120",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Sunday matinee divisional matchup. Gates open 90 minutes before first pitch. Fireworks if they win.",
    "image": "linear-gradient(135deg,#1e3a5f,#0E1830)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "3",
    "title": "Stone Arch Bridge Art Fair",
    "category": "festival",
    "venue": "Stone Arch Bridge",
    "address": "Father Hennepin Bluff Park",
    "city": "Minneapolis",
    "lat": 44.981,
    "lng": -93.256,
    "start": "2026-06-14T10:00",
    "end": "2026-06-14T18:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "260+ artists line the historic bridge over St. Anthony Falls. Food trucks, live music, riverfront views.",
    "image": "linear-gradient(135deg,#5a4a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "4",
    "title": "Como Zoo Sunset Safari",
    "category": "family",
    "venue": "Como Park Zoo",
    "address": "1225 Estabrook Dr",
    "city": "St Paul",
    "lat": 44.9826,
    "lng": -93.1517,
    "start": "2026-06-15T17:00",
    "end": "2026-06-15T20:00",
    "price": "$12 donation",
    "priceTier": "$",
    "ticketUrl": "",
    "description": "After-hours animal encounters, conservatory tours, and the Cafesjian Carousel lit up at dusk.",
    "image": "linear-gradient(135deg,#2e5a3e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "5",
    "title": "Can Can Wonderland Mini-Golf League",
    "category": "weird",
    "venue": "Can Can Wonderland",
    "address": "755 Prior Ave N",
    "city": "St Paul",
    "lat": 44.9636,
    "lng": -93.1733,
    "start": "2026-06-16T19:00",
    "end": "2026-06-16T22:00",
    "price": "$22",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Artist-designed 18-hole indoor mini-golf in a subterranean arcade wonderland. Cocktails, oddities, league night chaos.",
    "image": "linear-gradient(135deg,#5a2e4e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "6",
    "title": "Guthrie: A Midsummer Night's Dream",
    "category": "arts",
    "venue": "Guthrie Theater",
    "address": "818 S 2nd St",
    "city": "Minneapolis",
    "lat": 44.9786,
    "lng": -93.2558,
    "start": "2026-06-16T19:30",
    "end": "2026-06-16T22:15",
    "price": "$29–$89",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Shakespeare on the Wurtele Thrust Stage. Pre-show talk on the Endless Bridge overlooking the Mississippi.",
    "image": "linear-gradient(135deg,#5a3a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "7",
    "title": "Surly Brewing Patio Sessions",
    "category": "food",
    "venue": "Surly Brewing Co.",
    "address": "520 Malcolm Ave SE",
    "city": "Minneapolis",
    "lat": 44.9744,
    "lng": -93.2099,
    "start": "2026-06-17T18:00",
    "end": "2026-06-17T22:00",
    "price": "Free entry",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "Live local band on the beer garden stage, wood-fired pizza, and the Furious flowing. Dog-friendly yard.",
    "image": "linear-gradient(135deg,#5a4a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "8",
    "title": "Walker After Hours",
    "category": "arts",
    "venue": "Walker Art Center",
    "address": "725 Vineland Pl",
    "city": "Minneapolis",
    "lat": 44.9683,
    "lng": -93.2887,
    "start": "2026-06-18T20:00",
    "end": "2026-06-18T23:30",
    "price": "$25",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Galleries open late, DJ sets in the lobby, and the Sculpture Garden glowing under the Spoonbridge.",
    "image": "linear-gradient(135deg,#3a2d5e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "9",
    "title": "Twins vs. Guardians",
    "category": "sports",
    "venue": "Target Field",
    "address": "1 Twins Way",
    "city": "Minneapolis",
    "lat": 44.9817,
    "lng": -93.2776,
    "start": "2026-06-19T19:10",
    "end": "2026-06-19T22:00",
    "price": "$18–$120",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Friday night baseball under the lights. Postgame fireworks show over the right-field skyline.",
    "image": "linear-gradient(135deg,#1e3a5f,#0E1830)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "10",
    "title": "Lyn-Lake Street Fest",
    "category": "festival",
    "venue": "Lyndale & Lake",
    "address": "Lyndale Ave & Lake St",
    "city": "Minneapolis",
    "lat": 44.9483,
    "lng": -93.288,
    "start": "2026-06-20T11:00",
    "end": "2026-06-20T22:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "Two stages, 60 vendors, a beer garden, and the famous Soap Box Derby down the Lyndale hill.",
    "image": "linear-gradient(135deg,#5a4a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "11",
    "title": "Paisley Park: Purple Reign Tour",
    "category": "music",
    "venue": "Paisley Park",
    "address": "7801 Audubon Rd",
    "city": "Chanhassen",
    "lat": 44.8722,
    "lng": -93.556,
    "start": "2026-06-20T14:00",
    "end": "2026-06-20T16:00",
    "price": "$45",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Guided tour of Prince's studio complex — Studio A, the NPG Music Club, and the vault stories.",
    "image": "linear-gradient(135deg,#4a2e5e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "12",
    "title": "MN United vs. LAFC",
    "category": "sports",
    "venue": "Allianz Field",
    "address": "400 Snelling Ave N",
    "city": "St Paul",
    "lat": 44.953,
    "lng": -93.1655,
    "start": "2026-06-20T19:30",
    "end": "2026-06-20T21:30",
    "price": "$35–$160",
    "priceTier": "$$$",
    "ticketUrl": "",
    "description": "The Loons host LAFC at the Cathedral. Wonderwall singalout in the supporters' end. Get there early.",
    "image": "linear-gradient(135deg,#1e3a4f,#0E1830)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "13",
    "title": "Father's Day at the MN Zoo",
    "category": "family",
    "venue": "Minnesota Zoo",
    "address": "13000 Zoo Blvd",
    "city": "Apple Valley",
    "lat": 44.7717,
    "lng": -93.1955,
    "start": "2026-06-21T09:00",
    "end": "2026-06-21T17:00",
    "price": "$24 adult",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Treetop Trail, the Tropics Trail, and dad-gets-in-free promo. Bring a picnic for the Grizzly Coast lawn.",
    "image": "linear-gradient(135deg,#2e5a3e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "14",
    "title": "Sunday Jazz on the Plaza",
    "category": "music",
    "venue": "Mears Park",
    "address": "221 5th St E",
    "city": "St Paul",
    "lat": 44.9486,
    "lng": -93.0857,
    "start": "2026-06-21T16:00",
    "end": "2026-06-21T19:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "Lowertown's leafy park hosts a rotating lineup of Twin Cities jazz combos. Bring a blanket.",
    "image": "linear-gradient(135deg,#3a2d5e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "15",
    "title": "Northern Spark Night Festival",
    "category": "weird",
    "venue": "Downtown Riverfront",
    "address": "Water Power Park",
    "city": "Minneapolis",
    "lat": 44.9817,
    "lng": -93.2575,
    "start": "2026-06-21T21:00",
    "end": "2026-06-22T02:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "Dusk-to-dawn art happening — projection mapping on the grain silos, interactive light installations, and weirdness till 2am.",
    "image": "linear-gradient(135deg,#2e3a5e,#0E1830)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "16",
    "title": "Mia: Free First Thursday Late",
    "category": "arts",
    "venue": "Minneapolis Institute of Art",
    "address": "2400 Third Ave S",
    "city": "Minneapolis",
    "lat": 44.9583,
    "lng": -93.2737,
    "start": "2026-06-25T18:00",
    "end": "2026-06-25T21:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "Galleries open late with live music, gallery talks, and a cash bar in the rotunda. Always free admission.",
    "image": "linear-gradient(135deg,#5a3a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "17",
    "title": "Boom Island Beer Festival",
    "category": "food",
    "venue": "Boom Island Park",
    "address": "724 Sibley St NE",
    "city": "Minneapolis",
    "lat": 44.993,
    "lng": -93.271,
    "start": "2026-06-27T13:00",
    "end": "2026-06-27T17:00",
    "price": "$55",
    "priceTier": "$$$",
    "ticketUrl": "",
    "description": "40+ Minnesota breweries pouring on the riverbank, with the Aquatennial fireworks barge in view.",
    "image": "linear-gradient(135deg,#5a4a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "18",
    "title": "Twin Cities Pride Festival",
    "category": "festival",
    "venue": "Loring Park",
    "address": "1382 Willow St",
    "city": "Minneapolis",
    "lat": 44.9696,
    "lng": -93.2858,
    "start": "2026-06-27T10:00",
    "end": "2026-06-27T20:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "One of the nation's largest Pride celebrations — main stage, 400+ booths around the lake, and the Sunday parade down Hennepin.",
    "image": "linear-gradient(135deg,#5a2e4e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "19",
    "title": "Wild Prospect Showcase",
    "category": "sports",
    "venue": "Xcel Energy Center",
    "address": "199 W Kellogg Blvd",
    "city": "St Paul",
    "lat": 44.9447,
    "lng": -93.1009,
    "start": "2026-06-28T18:00",
    "end": "2026-06-28T20:30",
    "price": "$15",
    "priceTier": "$",
    "ticketUrl": "",
    "description": "See the next generation of Wild prospects scrimmage at The X. Autograph session on the concourse after.",
    "image": "linear-gradient(135deg,#1e3a5f,#0E1830)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "20",
    "title": "Open Streets Lyndale",
    "category": "festival",
    "venue": "Lyndale Avenue",
    "address": "Lyndale Ave S",
    "city": "Minneapolis",
    "lat": 44.941,
    "lng": -93.288,
    "start": "2026-06-28T11:00",
    "end": "2026-06-28T17:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "Two car-free miles of Lyndale handed over to bikes, buskers, pop-up patios, and a roving brass band.",
    "image": "linear-gradient(135deg,#5a4a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "21",
    "title": "Bauhaus Brew Labs Trivia",
    "category": "weird",
    "venue": "Bauhaus Brew Labs",
    "address": "1315 Tyler St NE",
    "city": "Minneapolis",
    "lat": 44.999,
    "lng": -93.247,
    "start": "2026-06-23T19:00",
    "end": "2026-06-23T21:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "Aggressively niche trivia in a NE Minneapolis taproom — rounds on Minnesota oddities, obscure 90s TV, and lake names.",
    "image": "linear-gradient(135deg,#5a2e4e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "22",
    "title": "Como Conservatory Sunday Concert",
    "category": "music",
    "venue": "Como Conservatory",
    "address": "1225 Estabrook Dr",
    "city": "St Paul",
    "lat": 44.9826,
    "lng": -93.1517,
    "start": "2026-06-22T16:00",
    "end": "2026-06-22T17:30",
    "price": "$5 donation",
    "priceTier": "$",
    "ticketUrl": "",
    "description": "Chamber music among the palms in the Sunken Garden. A St. Paul tradition since 1915.",
    "image": "linear-gradient(135deg,#3a2d5e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "23",
    "title": "Saints vs. Iowa Cubs",
    "category": "sports",
    "venue": "CHS Field",
    "address": "360 Broadway St",
    "city": "St Paul",
    "lat": 44.9483,
    "lng": -93.0826,
    "start": "2026-06-24T19:05",
    "end": "2026-06-24T21:30",
    "price": "$12–$30",
    "priceTier": "$",
    "ticketUrl": "",
    "description": "Triple-A baseball with a pig mascot, a nun giving massages, and the best ballpark beer list in the metro.",
    "image": "linear-gradient(135deg,#1e3a5f,#0E1830)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "24",
    "title": "Powderhorn Art Fair Preview",
    "category": "arts",
    "venue": "Powderhorn Park",
    "address": "3400 15th Ave S",
    "city": "Minneapolis",
    "lat": 44.9407,
    "lng": -93.252,
    "start": "2026-06-26T17:00",
    "end": "2026-06-26T21:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "Lakeside preview night for one of the metro's most beloved neighborhood art fairs. 190 artists, food, and music.",
    "image": "linear-gradient(135deg,#5a3a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "25",
    "title": "Midtown Global Market Tasting",
    "category": "food",
    "venue": "Midtown Global Market",
    "address": "920 E Lake St",
    "city": "Minneapolis",
    "lat": 44.9483,
    "lng": -93.262,
    "start": "2026-06-15T12:00",
    "end": "2026-06-15T15:00",
    "price": "$30",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Guided tasting crawl through the market's 20+ international stalls — East African, Mexican, Vietnamese, and more.",
    "image": "linear-gradient(135deg,#5a4a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "26",
    "title": "Lake Harriet Bandshell: Twin Cities Symphony",
    "category": "music",
    "venue": "Lake Harriet Bandshell",
    "address": "4135 W Lake Harriet Pkwy",
    "city": "Minneapolis",
    "lat": 44.9226,
    "lng": -93.307,
    "start": "2026-06-18T19:30",
    "end": "2026-06-18T21:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "Free orchestral concert at the storied lakeside bandshell. Bring chairs, watch the sailboats, stay for sunset.",
    "image": "linear-gradient(135deg,#3a2d5e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "27",
    "title": "Mall of America Nickelodeon Night",
    "category": "family",
    "venue": "Mall of America",
    "address": "60 E Broadway",
    "city": "Bloomington",
    "lat": 44.8548,
    "lng": -93.2422,
    "start": "2026-06-19T17:00",
    "end": "2026-06-19T21:00",
    "price": "$45 wristband",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "After-hours run of Nickelodeon Universe — every coaster, character meet-and-greets, and shorter lines.",
    "image": "linear-gradient(135deg,#2e5a3e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "28",
    "title": "Hippie Hour Vintage Market",
    "category": "weird",
    "venue": "The Hook & Ladder",
    "address": "3010 Minnehaha Ave",
    "city": "Minneapolis",
    "lat": 44.9495,
    "lng": -93.23,
    "start": "2026-06-29T13:00",
    "end": "2026-06-29T18:00",
    "price": "Free",
    "priceTier": "Free",
    "ticketUrl": "",
    "description": "40 vintage and oddity vendors, a record swap, tarot readers, and a patio band at this beloved Longfellow venue.",
    "image": "linear-gradient(135deg,#5a2e4e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "29",
    "title": "Twins vs. Tigers",
    "category": "sports",
    "venue": "Target Field",
    "address": "1 Twins Way",
    "city": "Minneapolis",
    "lat": 44.9817,
    "lng": -93.2776,
    "start": "2026-06-30T18:40",
    "end": "2026-06-30T21:30",
    "price": "$18–$120",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "Final homestand game before the road trip. Dollar dog night on the main concourse.",
    "image": "linear-gradient(135deg,#1e3a5f,#0E1830)",
    "sourceUrl": "",
    "status": "published"
  },
  {
    "id": "30",
    "title": "Fitzgerald Theater: Live Storytelling",
    "category": "arts",
    "venue": "Fitzgerald Theater",
    "address": "10 Exchange St E",
    "city": "St Paul",
    "lat": 44.9472,
    "lng": -93.0972,
    "start": "2026-06-13T19:30",
    "end": "2026-06-13T21:30",
    "price": "$28",
    "priceTier": "$$",
    "ticketUrl": "",
    "description": "An evening of true, unscripted stories from Twin Cities tellers in the oldest surviving theater in St. Paul.",
    "image": "linear-gradient(135deg,#5a3a2e,#16243f)",
    "sourceUrl": "",
    "status": "published"
  }
];
